### ISSUE TITLE
Images from pages loaded in iframes in Laravel app are showing in Buggregator 

### ISSUE THREAD

**Issue by binaryfire** [buggregator/frontend#110] opened 2024-01-19 07:19 UTC
Hi guys

I've got an app which loads pages in an iframe (and uses postMessage to communicate with them). For some reason the images from the pages loaded in the iframe often appear in Buggregator:

<img width="1091" alt="image" src="https://github.com/buggregator/frontend/assets/5361908/d0ee1748-326e-4d2f-a0d7-41daeeca142f">

**Comment by Kreezag** [comment] 2024-08-16 13:36
Hi @binaryfire Sorry for the long answer for this issue.

Could you share with us if the issue is still actual?

I did short investigate and the potential source of problem was in iframe representation. Since release https://github.com/buggregator/frontend/releases/tag/1.15.2 we have the different approach to render iframes so this issue may have become irrelevant.

**Comment by Kreezag** [comment] 2024-08-22 18:34
closed as оbsolete

**Closed by Kreezag** 2024-08-22 18:34 UTC
